# Generated by Django 6.0.2 on 2026-02-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_genre_text'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='users.profile'),
        ),
    ]
